apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: dapr-iot
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
    - name: region
      value: "us-east-1"  # update to match your Terraform var.aws_region
